### PR TITLE
Fixed broken toolbar

### PR DESCRIPTION
**Pull request by amercier**
qunit-notifications v0.0.5 fixes a bug that makes the toolbar not working.

### CODE REVIEW

**Comment by amercier** [comment]
Please merge :)

**Comment by amercier** [comment]
Please merge :)

**Comment by bcardarella** [comment]
@amercier I just added you to the repo, I'm out of the office for the next few hours. Do you want to handle the version tag for Bower?

**Comment by amercier** [comment]
Sure. Thanks

**Comment by amercier** [comment]
Published v0.0.6

Also, please note that I removed `version` from `bower.json`. According to [official documentation](https://github.com/bower/bower.json-spec#version), this is unnecessary since Bower is using tags instead:

> ### version
> 
> Ignored by Bower as git tags are used instead.
> 
> Intended to be used in the future when Bower gets a real registry where you can publish actual packages, but **lfor now just eave it out**.

**Comment by bcardarella** [comment]
:+1:

**Pull request merged**
